PrimeFaces.locales ['hr'] = {
    closeText: 'Zatvori',
    prevText: 'Natrag',
    nextText: 'Naprijed',
    monthNames: ['Siječanj', 'Veljača', 'Ožujak', 'Travanj', 'Svibanj', 'Lipanj', 'Srpanj', 'Kolovoz', 'Rujan', 'Listopad', 'Studeni', 'Prosinac' ],
    monthNamesShort: ['Sij', 'Velj', 'Ožu', 'Tra', 'Svi', 'Lip', 'Srp', 'Kol', 'Ruj', 'Lis', 'Stu', 'Pro' ],
    dayNames: ['Nedjelja', 'Ponedjeljak', 'Utorak', 'Srijeda', 'Četvrtak', 'Petak', 'Subota'],
    dayNamesShort: ['Ned', 'Pon', 'Uto', 'Sre', 'Čet', 'Pet', 'Sub'],
    dayNamesMin: ['N', 'P', 'U', 'S ', 'Č', 'P ', 'S'],
    weekHeader: 'Tjedan',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix:'',
    timeOnlyTitle: 'Samo Vrijeme',
    timeText: 'Vrijeme',
    hourText: 'Sat',
    minuteText: 'Minuta',
    secondText: 'Sekunda',
    currentText: 'Danas',
    ampm: false,
    month: 'Mjesec',
    week: 'tjedan',
    day: 'Dan',
    allDayText: 'Cijeli Dan'
};
